# docker compose --file docker/compose.yml up --build

services:
  python3.12:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    command: python /usr/src/app/tests/run_tests.py

  python3.13:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      args:
        PYTHON_VERSION: "3.13"
    command: python /usr/src/app/tests/run_tests.py

